# Generated by Django 5.2.7 on 2025-12-10 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocinaApp', '0001_initial'),
        ('mainApp', '0008_alter_reserva_estado_bloqueomesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando el pedido fue entregado', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_listo',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando el pedido pasó a estado LISTO', null=True),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_listo'], name='cocinaApp_p_fecha_l_056400_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_entregado'], name='cocinaApp_p_fecha_e_5225fe_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', 'fecha_listo'], name='cocinaApp_p_estado_eddd09_idx'),
        ),
    ]
