# Generated by Django 5.2.7 on 2025-12-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocinaApp', '0002_add_fecha_listo_entregado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cancelacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la cancelación')),
                ('motivo', models.TextField(help_text='Motivo de la cancelación', max_length=500)),
                ('mesa_numero', models.IntegerField()),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos_resumen', models.TextField(blank=True, help_text='Resumen de productos del pedido (snapshot en texto)')),
                ('productos_detalle', models.JSONField(blank=True, default=list, help_text='Detalle estructurado de productos (snapshot en JSON)')),
                ('cancelado_por', models.ForeignKey(help_text='Usuario que canceló el pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cancelados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(help_text='Pedido cancelado', on_delete=django.db.models.deletion.CASCADE, related_name='cancelacion', to='cocinaApp.pedido')),
            ],
            options={
                'verbose_name': 'Cancelación de Pedido',
                'verbose_name_plural': 'Cancelaciones de Pedidos',
                'ordering': ['-fecha_cancelacion'],
                'indexes': [models.Index(fields=['fecha_cancelacion'], name='cocinaApp_p_fecha_c_f2a411_idx'), models.Index(fields=['cancelado_por', 'fecha_cancelacion'], name='cocinaApp_p_cancela_4463e0_idx')],
            },
        ),
    ]
