# Generated by Django 5.2.7 on 2025-12-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú')),
            ],
            options={
                'verbose_name': 'Categoría de Menú',
                'verbose_name_plural': 'Categorías de Menú',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('gr', 'Gramos'), ('kg', 'Kilogramos'), ('un', 'Unidades'), ('lt', 'Litros'), ('ml', 'Mililitros')], default='un', max_length=20)),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad disponible en inventario', max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad mínima antes de alerta', max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Precio de compra por unidad', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platos/')),
                ('tiempo_preparacion', models.PositiveIntegerField(default=15, help_text='Tiempo estimado de preparación en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platos', to='menuApp.categoriamenu')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=3, help_text='Cantidad de ingrediente necesaria para preparar el plato', max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='menuApp.ingrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='menuApp.plato')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'unique_together': {('plato', 'ingrediente')},
            },
        ),
    ]
