# Generated by Django 5.2.7 on 2025-11-15 02:51

import encrypted_model_fields.fields
from django.db import migrations, models


def limpiar_emails_vacios(apps, schema_editor):
    """Convertir emails vacíos a NULL antes de aplicar unique constraint"""
    Perfil = apps.get_model('mainApp', 'Perfil')
    # Convertir strings vacíos a None (NULL en DB)
    perfiles_actualizados = Perfil.objects.filter(email='').update(email=None)
    print(f'Convertidos {perfiles_actualizados} emails vacíos a NULL')


def reverse_limpiar_emails(apps, schema_editor):
    """Revertir: convertir NULL a string vacío"""
    Perfil = apps.get_model('mainApp', 'Perfil')
    Perfil.objects.filter(email__isnull=True).update(email='')


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_reserva_num_personas_minimo_1_and_more'),
    ]

    operations = [
        # Paso 1: Agregar null=True sin unique (permite NULL temporalmente)
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='RUT del usuario (encriptado)', null=True),
        ),

        # Paso 2: Limpiar datos (convertir '' a NULL)
        migrations.RunPython(limpiar_emails_vacios, reverse_limpiar_emails),

        # Paso 3: Ahora sí agregar unique constraint
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='RUT del usuario (encriptado)', null=True, unique=True),
        ),

        # Paso 4: Actualizar notas con max_length
        migrations.AlterField(
            model_name='reserva',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas o requerimientos especiales (máx 500 caracteres)', max_length=500),
        ),
    ]
