# Generated by Django 5.2.7 on 2025-11-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_reserva_idx_cliente_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True),
        ),
    ]
