# Generated by Django 5.2.7 on 2025-11-22 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_perfil_es_invitado_perfil_token_activacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15),
        ),
        migrations.CreateModel(
            name='BloqueoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del bloqueo')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del bloqueo')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio (dejar vacío para bloqueo de día completo)', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de fin (dejar vacío para bloqueo de día completo)', null=True)),
                ('motivo', models.CharField(help_text='Motivo del bloqueo', max_length=200)),
                ('categoria', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('evento_privado', 'Evento Privado'), ('reparacion', 'Reparación'), ('reserva_especial', 'Reserva Especial'), ('otro', 'Otro')], default='otro', help_text='Categoría del bloqueo', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales (máx 500 caracteres)', max_length=500)),
                ('tipo_recurrencia', models.CharField(choices=[('ninguna', 'Sin Recurrencia'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='ninguna', help_text='Tipo de recurrencia del bloqueo', max_length=10)),
                ('activo', models.BooleanField(default=True, help_text='Si el bloqueo está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mesa', models.ForeignKey(help_text='Mesa a bloquear', on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='mainApp.mesa')),
                ('usuario_creador', models.ForeignKey(help_text='Usuario que creó el bloqueo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueo de Mesa',
                'verbose_name_plural': 'Bloqueos de Mesas',
                'ordering': ['-fecha_inicio', '-hora_inicio'],
                'indexes': [models.Index(fields=['mesa', 'fecha_inicio', 'fecha_fin'], name='mainApp_blo_mesa_id_e2b2f2_idx'), models.Index(fields=['activo'], name='mainApp_blo_activo_47a91f_idx'), models.Index(fields=['categoria'], name='mainApp_blo_categor_dc35f3_idx')],
            },
        ),
    ]
