# Generated by Django 5.2.7 on 2025-11-15 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_reserva', 'estado'], name='mainApp_res_fecha_r_da5298_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='mainApp_res_estado_adfd68_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['-fecha_reserva', '-hora_inicio'], name='mainApp_res_fecha_r_c8bee4_idx'),
        ),
    ]
