# Generated by Django 5.2.7 on 2025-11-15 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_reserva_mainapp_res_fecha_r_da5298_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('num_personas__gte', 1)), name='num_personas_minimo_1'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('num_personas__lte', 50)), name='num_personas_maximo_50'),
        ),
    ]
