# Generated by Django 5.2.7 on 2025-11-15 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_perfil_email_alter_perfil_rut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cliente', 'fecha_reserva'], name='idx_cliente_fecha'),
        ),
    ]
