# Generated by Django 5.2.7 on 2025-11-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_reserva_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='es_invitado',
            field=models.BooleanField(default=False, help_text='Usuario creado sin contraseña para reserva pública'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='token_activacion',
            field=models.CharField(blank=True, help_text='Token único para acceso sin login y activación de cuenta', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='token_expira',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del token (48 horas desde creación)', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='token_usado',
            field=models.BooleanField(default=False, help_text='Indica si el token de activación ya fue usado para crear cuenta'),
        ),
    ]
